{"name": "Ошибка 404 Not Found при запросе на принятие заказа c несуществующим ID заказа.", "status": "passed", "description": "Создаем курьера фикстурой courier_id и получаем его ID. Отправляется PUT запрос на ручку /api/v1/orders/accept/orderID?courierId=CourierID c несуществующим ID заказа. Проверяем, что код ответа 404 Not Found и текст ответа \"Заказа с таким id не существует\" Курьер удаляется из системы фикстурой courier_id.", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1738945773277, "stop": 1738945773277}, {"name": "PUT request без payload", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/orders/accept/574215887?courierId=465007'"}], "start": 1738945773277, "stop": 1738945773343}], "attachments": [{"name": "stdout", "source": "fc705891-97ee-4f98-950e-1db408cee38b-attachment.txt", "type": "text/plain"}], "start": 1738945773276, "stop": 1738945773344, "uuid": "b16f88b3-8164-4c8d-bd93-16c67573347e", "historyId": "439c3fad956072105fea1d5fed35e9ab", "testCaseId": "439c3fad956072105fea1d5fed35e9ab", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_valid_courier_id_not_valid_order_id_shows_error_404", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('class_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "14568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}