{"name": "Ошибка 404 Not Found при запросе на удаление курьера c несуществующим id.", "status": "passed", "description": "Отправлям DELETE запрос на ручку DELETE/api/v1/courier/:id c несуществующим id. Проверяем, что ответ 404 Not Found и сообщение в ответе \"Курьера с таким id нет\"", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1738945779206, "stop": 1738945779206}, {"name": "DELETE request.", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/courier/847955757'"}, {"name": "payload", "value": "{'id': '847955757'}"}], "start": 1738945779206, "stop": 1738945779277}], "start": 1738945779206, "stop": 1738945779277, "uuid": "63e103fc-15a4-478c-9a3a-8b2073253a93", "historyId": "f07b12503581d22ddde1c52790437073", "testCaseId": "f07b12503581d22ddde1c52790437073", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_delete_courier_id_not_exists_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "14568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}