{"name": "Ошибка 404 Not Found при запросе на принятие заказа c несуществующим ID курьера.", "status": "passed", "description": "Создаем заказ фикстурой order_confirmed. Отправляется PUT запрос на ручку /api/v1/orders/accept/OrderID?courierId=CourierID c несуществующим ID курьера. Проверяем, что код ответа 404 Not Found и текст ответа \"Курьера с таким id не существует\"", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1738945773044, "stop": 1738945773044}, {"name": "PUT request без payload", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/orders/accept/611575?courierId=220383521'"}], "start": 1738945773044, "stop": 1738945773131}], "attachments": [{"name": "stdout", "source": "f0858608-3ac9-4e20-adc8-faf5c6c802d3-attachment.txt", "type": "text/plain"}], "start": 1738945773043, "stop": 1738945773132, "uuid": "99b9675a-8769-4604-b4ac-cb0095c69588", "historyId": "faa092fd401fb4cee5bf42ea537dc77c", "testCaseId": "faa092fd401fb4cee5bf42ea537dc77c", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_valid_order_id_not_valid_courier_id_shows_error_404", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('class_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "14568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}